In [7]:
from pathlib import Path
import pandas as pd

PROCESSED_DIR = Path("../data/processed")

final_daily_df = pd.read_parquet(
    PROCESSED_DIR / "air_pollution_weather_daily_master.parquet"
)

final_daily_df["date"] = pd.to_datetime(final_daily_df["date"])

print(final_daily_df.shape)
display(final_daily_df[["station_id", "station_name", "date", "pm25"]].head())

(12271, 73)

   station_id station_name       date  pm25
0        2919    Gazi Baba 2016-12-11   NaN
1        2919    Gazi Baba 2016-12-12   NaN
2        2919    Gazi Baba 2016-12-13   NaN
3        2919    Gazi Baba 2016-12-14   NaN
4        2919    Gazi Baba 2016-12-15   NaN

In [8]:
pm25_yearly_coverage_df = (
    final_daily_df
    .assign(
        year=final_daily_df["date"].dt.year,
        pm25_available=final_daily_df["pm25"].notna()
    )
    .groupby(
        ["station_id", "station_name", "year"],
        as_index=False
    )
    .agg(
        total_station_days=("date", "size"),
        pm25_days_available=("pm25_available", "sum"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

pm25_yearly_coverage_df["pm25_days_missing"] = (
    pm25_yearly_coverage_df["total_station_days"]
    - pm25_yearly_coverage_df["pm25_days_available"]
)

pm25_yearly_coverage_df["pm25_coverage_percent"] = (
    pm25_yearly_coverage_df["pm25_days_available"]
    / pm25_yearly_coverage_df["total_station_days"]
    * 100
).round(2)

pm25_yearly_coverage_df = (
    pm25_yearly_coverage_df
    .sort_values(["station_name", "year"])
    .reset_index(drop=True)
)

display(pm25_yearly_coverage_df)

,station_id,station_name,year,total_station_days,pm25_days_available,first_date,last_date,pm25_days_missing,pm25_coverage_percent
0,2996,Centar,2016,8,0,2016-12-11,2016-12-18,8,0.00
1,2996,Centar,2017,187,0,2017-02-19,2017-12-31,187,0.00
2,2996,Centar,2018,255,185,2018-01-01,2018-12-31,70,72.55
3,2996,Centar,2019,305,239,2019-01-02,2019-12-31,66,78.36
4,2996,Centar,2020,265,259,2020-01-01,2020-12-30,6,97.74
5,2996,Centar,2021,239,202,2021-01-01,2021-12-31,37,84.52
6,2996,Centar,2022,266,185,2022-01-01,2022-12-20,81,69.55
7,2996,Centar,2023,199,0,2023-01-04,2023-12-31,199,0.00
8,2996,Centar,2024,195,122,2024-01-01,2024-08-25,73,62.56
9,2996,Centar,2025,92,92,2025-09-19,2025-12-31,0,100.00
10,2919,Gazi Baba,2016,8,0,2016-12-11,2016-12-18,8,0.00
11,2919,Gazi Baba,2017,223,0,2017-01-11,2017-12-31,223,0.00
12,2919,Gazi Baba,2018,253,0,2018-01-01,2018-12-31,253,0.00
13,2919,Gazi Baba,2019,319,0,2019-01-02,2019-12-31,319,0.00
14,2919,Gazi Baba,2020,274,0,2020-01-01,2020-12-30,274,0.00
15,2919,Gazi Baba,2021,238,0,2021-01-01,2021-12-31,238,0.00
16,2919,Gazi Baba,2022,289,0,2022-01-01,2022-12-28,289,0.00
17,2919,Gazi Baba,2023,202,167,2023-01-04,2023-12-31,35,82.67
18,2919,Gazi Baba,2024,206,206,2024-01-01,2024-08-25,0,100.00
19,2919,Gazi Baba,2025,92,90,2025-09-19,2025-12-31,2,97.83
20,2977,Karpos,2016,8,0,2016-12-11,2016-12-18,8,0.00
21,2977,Karpos,2017,228,0,2017-01-06,2017-12-31,228,0.00
22,2977,Karpos,2018,260,122,2018-01-01,2018-12-31,138,46.92
23,2977,Karpos,2019,301,295,2019-01-02,2019-12-31,6,98.01
24,2977,Karpos,2020,275,275,2020-01-01,2020-12-30,0,100.00
25,2977,Karpos,2021,245,235,2021-01-01,2021-12-31,10,95.92
26,2977,Karpos,2022,274,189,2022-01-01,2022-12-20,85,68.98
27,2977,Karpos,2023,202,0,2023-01-04,2023-12-31,202,0.00
28,2977,Karpos,2024,198,128,2024-01-01,2024-08-25,70,64.65
29,2977,Karpos,2025,90,90,2025-09-19,2025-12-31,0,100.00
30,2976,Lisice,2016,7,0,2016-12-11,2016-12-18,7,0.00
31,2976,Lisice,2017,211,0,2017-01-12,2017-12-31,211,0.00
32,2976,Lisice,2018,252,0,2018-01-01,2018-12-31,252,0.00
33,2976,Lisice,2019,318,0,2019-01-02,2019-12-31,318,0.00
34,2976,Lisice,2020,278,0,2020-01-01,2020-12-30,278,0.00
35,2976,Lisice,2021,242,0,2021-01-01,2021-12-31,242,0.00
36,2976,Lisice,2022,269,0,2022-01-01,2022-12-20,269,0.00
37,2976,Lisice,2023,198,163,2023-01-04,2023-12-31,35,82.32
38,2976,Lisice,2024,199,199,2024-01-01,2024-08-25,0,100.00
39,2976,Lisice,2025,93,93,2025-09-19,2025-12-31,0,100.00
40,2978,Miladinovci,2016,8,0,2016-12-11,2016-12-18,8,0.00
41,2978,Miladinovci,2017,224,0,2017-01-08,2017-12-31,224,0.00
42,2978,Miladinovci,2018,256,0,2018-01-01,2018-12-31,256,0.00
43,2978,Miladinovci,2019,318,0,2019-01-02,2019-12-31,318,0.00
44,2978,Miladinovci,2020,266,0,2020-01-01,2020-12-30,266,0.00
45,2978,Miladinovci,2021,242,0,2021-01-01,2021-12-31,242,0.00
46,2978,Miladinovci,2022,272,0,2022-01-01,2022-12-20,272,0.00
47,2978,Miladinovci,2023,203,162,2023-01-04,2023-12-31,41,79.80
48,2978,Miladinovci,2024,206,204,2024-01-01,2024-08-25,2,99.03
49,2978,Miladinovci,2025,93,93,2025-09-19,2025-12-31,0,100.00
50,2979,Rektorat,2016,6,0,2016-12-11,2016-12-18,6,0.00
51,2979,Rektorat,2017,209,0,2017-01-13,2017-12-31,209,0.00
52,2979,Rektorat,2018,254,0,2018-01-01,2018-12-31,254,0.00
53,2979,Rektorat,2019,317,0,2019-01-02,2019-12-31,317,0.00
54,2979,Rektorat,2020,279,0,2020-01-01,2020-12-30,279,0.00
55,2979,Rektorat,2021,242,0,2021-01-01,2021-12-31,242,0.00
56,2979,Rektorat,2022,271,0,2022-01-01,2022-12-20,271,0.00
57,2979,Rektorat,2023,44,0,2023-01-04,2023-12-31,44,0.00
58,2979,Rektorat,2024,206,0,2024-01-01,2024-08-25,206,0.00
59,2979,Rektorat,2025,92,0,2025-09-19,2025-12-31,92,0.00

In [9]:
pm25_yearly_coverage_df = (
    final_daily_df
    .assign(
        year=final_daily_df["date"].dt.year,
        pm25_available=final_daily_df["pm25"].notna()
    )
    .groupby(
        ["station_id", "station_name", "year"],
        as_index=False
    )
    .agg(
        total_station_days=("date", "size"),
        pm25_days_available=("pm25_available", "sum"),
        first_date=("date", "min"),
        last_date=("date", "max"),
    )
)

pm25_yearly_coverage_df["pm25_days_missing"] = (
    pm25_yearly_coverage_df["total_station_days"]
    - pm25_yearly_coverage_df["pm25_days_available"]
)

pm25_yearly_coverage_df["pm25_coverage_percent"] = (
    pm25_yearly_coverage_df["pm25_days_available"]
    / pm25_yearly_coverage_df["total_station_days"]
    * 100
).round(2)

pm25_yearly_coverage_df = (
    pm25_yearly_coverage_df
    .sort_values(["station_name", "year"])
    .reset_index(drop=True)
)

display(pm25_yearly_coverage_df)

,station_id,station_name,year,total_station_days,pm25_days_available,first_date,last_date,pm25_days_missing,pm25_coverage_percent
0,2996,Centar,2016,8,0,2016-12-11,2016-12-18,8,0.00
1,2996,Centar,2017,187,0,2017-02-19,2017-12-31,187,0.00
2,2996,Centar,2018,255,185,2018-01-01,2018-12-31,70,72.55
3,2996,Centar,2019,305,239,2019-01-02,2019-12-31,66,78.36
4,2996,Centar,2020,265,259,2020-01-01,2020-12-30,6,97.74
5,2996,Centar,2021,239,202,2021-01-01,2021-12-31,37,84.52
6,2996,Centar,2022,266,185,2022-01-01,2022-12-20,81,69.55
7,2996,Centar,2023,199,0,2023-01-04,2023-12-31,199,0.00
8,2996,Centar,2024,195,122,2024-01-01,2024-08-25,73,62.56
9,2996,Centar,2025,92,92,2025-09-19,2025-12-31,0,100.00
10,2919,Gazi Baba,2016,8,0,2016-12-11,2016-12-18,8,0.00
11,2919,Gazi Baba,2017,223,0,2017-01-11,2017-12-31,223,0.00
12,2919,Gazi Baba,2018,253,0,2018-01-01,2018-12-31,253,0.00
13,2919,Gazi Baba,2019,319,0,2019-01-02,2019-12-31,319,0.00
14,2919,Gazi Baba,2020,274,0,2020-01-01,2020-12-30,274,0.00
15,2919,Gazi Baba,2021,238,0,2021-01-01,2021-12-31,238,0.00
16,2919,Gazi Baba,2022,289,0,2022-01-01,2022-12-28,289,0.00
17,2919,Gazi Baba,2023,202,167,2023-01-04,2023-12-31,35,82.67
18,2919,Gazi Baba,2024,206,206,2024-01-01,2024-08-25,0,100.00
19,2919,Gazi Baba,2025,92,90,2025-09-19,2025-12-31,2,97.83
20,2977,Karpos,2016,8,0,2016-12-11,2016-12-18,8,0.00
21,2977,Karpos,2017,228,0,2017-01-06,2017-12-31,228,0.00
22,2977,Karpos,2018,260,122,2018-01-01,2018-12-31,138,46.92
23,2977,Karpos,2019,301,295,2019-01-02,2019-12-31,6,98.01
24,2977,Karpos,2020,275,275,2020-01-01,2020-12-30,0,100.00
25,2977,Karpos,2021,245,235,2021-01-01,2021-12-31,10,95.92
26,2977,Karpos,2022,274,189,2022-01-01,2022-12-20,85,68.98
27,2977,Karpos,2023,202,0,2023-01-04,2023-12-31,202,0.00
28,2977,Karpos,2024,198,128,2024-01-01,2024-08-25,70,64.65
29,2977,Karpos,2025,90,90,2025-09-19,2025-12-31,0,100.00
30,2976,Lisice,2016,7,0,2016-12-11,2016-12-18,7,0.00
31,2976,Lisice,2017,211,0,2017-01-12,2017-12-31,211,0.00
32,2976,Lisice,2018,252,0,2018-01-01,2018-12-31,252,0.00
33,2976,Lisice,2019,318,0,2019-01-02,2019-12-31,318,0.00
34,2976,Lisice,2020,278,0,2020-01-01,2020-12-30,278,0.00
35,2976,Lisice,2021,242,0,2021-01-01,2021-12-31,242,0.00
36,2976,Lisice,2022,269,0,2022-01-01,2022-12-20,269,0.00
37,2976,Lisice,2023,198,163,2023-01-04,2023-12-31,35,82.32
38,2976,Lisice,2024,199,199,2024-01-01,2024-08-25,0,100.00
39,2976,Lisice,2025,93,93,2025-09-19,2025-12-31,0,100.00
40,2978,Miladinovci,2016,8,0,2016-12-11,2016-12-18,8,0.00
41,2978,Miladinovci,2017,224,0,2017-01-08,2017-12-31,224,0.00
42,2978,Miladinovci,2018,256,0,2018-01-01,2018-12-31,256,0.00
43,2978,Miladinovci,2019,318,0,2019-01-02,2019-12-31,318,0.00
44,2978,Miladinovci,2020,266,0,2020-01-01,2020-12-30,266,0.00
45,2978,Miladinovci,2021,242,0,2021-01-01,2021-12-31,242,0.00
46,2978,Miladinovci,2022,272,0,2022-01-01,2022-12-20,272,0.00
47,2978,Miladinovci,2023,203,162,2023-01-04,2023-12-31,41,79.80
48,2978,Miladinovci,2024,206,204,2024-01-01,2024-08-25,2,99.03
49,2978,Miladinovci,2025,93,93,2025-09-19,2025-12-31,0,100.00
50,2979,Rektorat,2016,6,0,2016-12-11,2016-12-18,6,0.00
51,2979,Rektorat,2017,209,0,2017-01-13,2017-12-31,209,0.00
52,2979,Rektorat,2018,254,0,2018-01-01,2018-12-31,254,0.00
53,2979,Rektorat,2019,317,0,2019-01-02,2019-12-31,317,0.00
54,2979,Rektorat,2020,279,0,2020-01-01,2020-12-30,279,0.00
55,2979,Rektorat,2021,242,0,2021-01-01,2021-12-31,242,0.00
56,2979,Rektorat,2022,271,0,2022-01-01,2022-12-20,271,0.00
57,2979,Rektorat,2023,44,0,2023-01-04,2023-12-31,44,0.00
58,2979,Rektorat,2024,206,0,2024-01-01,2024-08-25,206,0.00
59,2979,Rektorat,2025,92,0,2025-09-19,2025-12-31,92,0.00

In [10]:
PROJECT_START = "2016-01-01"
PROJECT_END = "2025-12-31"

stations_df = (
    final_daily_df[
        ["station_id", "station_name"]
    ]
    .drop_duplicates()
    .sort_values("station_name")
    .reset_index(drop=True)
)

all_dates_df = pd.DataFrame({
    "date": pd.date_range(
        start=PROJECT_START,
        end=PROJECT_END,
        freq="D"
    )
})

station_calendar_df = (
    stations_df
    .merge(all_dates_df, how="cross")
)

pm25_values_df = (
    final_daily_df[
        [
            "station_id",
            "station_name",
            "date",
            "pm25",
            "pm25_valid_day",
            "pm25_observed_hours",
        ]
    ]
    .drop_duplicates(
        subset=[
            "station_id",
            "date",
        ]
    )
)

pm25_calendar_df = (
    station_calendar_df
    .merge(
        pm25_values_df,
        on=[
            "station_id",
            "station_name",
            "date",
        ],
        how="left",
    )
    .sort_values(["station_id", "date"])
    .reset_index(drop=True)
)

pm25_calendar_df["pm25_available"] = (
    pm25_calendar_df["pm25"].notna()
)

display(pm25_calendar_df.head())

,station_id,station_name,date,pm25,pm25_valid_day,pm25_observed_hours,pm25_available
0,2919,Gazi Baba,2016-01-01,NaN,NaN,NaN,False
1,2919,Gazi Baba,2016-01-02,NaN,NaN,NaN,False
2,2919,Gazi Baba,2016-01-03,NaN,NaN,NaN,False
3,2919,Gazi Baba,2016-01-04,NaN,NaN,NaN,False
4,2919,Gazi Baba,2016-01-05,NaN,NaN,NaN,False

In [11]:
def find_missing_periods(df, station_id, station_name):
    station_df = (
        df[
            df["station_id"] == station_id
        ]
        .sort_values("date")
        .copy()
    )

    station_df["is_missing"] = (
        ~station_df["pm25_available"]
    )

    station_df["missing_group"] = (
        station_df["is_missing"]
        .ne(station_df["is_missing"].shift())
        .cumsum()
    )

    periods = (
        station_df[
            station_df["is_missing"]
        ]
        .groupby("missing_group", as_index=False)
        .agg(
            missing_start=("date", "min"),
            missing_end=("date", "max"),
            missing_days=("date", "size"),
        )
    )

    periods["station_id"] = station_id
    periods["station_name"] = station_name

    return periods[
        [
            "station_id",
            "station_name",
            "missing_start",
            "missing_end",
            "missing_days",
        ]
    ]

missing_period_parts = []

for station in stations_df.itertuples(index=False):
    station_periods_df = find_missing_periods(
        pm25_calendar_df,
        station_id=station.station_id,
        station_name=station.station_name,
    )

    missing_period_parts.append(station_periods_df)

pm25_missing_periods_df = pd.concat(
    missing_period_parts,
    ignore_index=True,
)

pm25_missing_periods_df = (
    pm25_missing_periods_df
    .sort_values(
        ["station_name", "missing_start"]
    )
    .reset_index(drop=True)
)

display(pm25_missing_periods_df)

     station_id station_name missing_start missing_end  missing_days
0          2996       Centar    2016-01-01  2018-03-06           796
1          2996       Centar    2018-03-10  2018-03-10             1
2          2996       Centar    2018-03-12  2018-04-18            38
3          2996       Centar    2018-05-04  2018-05-04             1
4          2996       Centar    2018-05-07  2018-05-07             1
..          ...          ...           ...         ...           ...
465        2978  Miladinovci    2025-10-06  2025-10-07             2
466        2978  Miladinovci    2025-10-15  2025-10-16             2
467        2978  Miladinovci    2025-11-06  2025-11-07             2
468        2978  Miladinovci    2025-11-28  2025-12-01             4
469        2979     Rektorat    2016-01-01  2025-12-31          3653

[470 rows x 5 columns]

In [12]:
LONG_GAP_DAYS = 7

pm25_long_gaps_df = pm25_missing_periods_df[
    pm25_missing_periods_df["missing_days"] >= LONG_GAP_DAYS
].copy()

pm25_long_gaps_df = (
    pm25_long_gaps_df
    .sort_values(
        ["station_name", "missing_days"],
        ascending=[True, False],
    )
    .reset_index(drop=True)
)

display(pm25_long_gaps_df)

    station_id station_name missing_start missing_end  missing_days
0         2996       Centar    2016-01-01  2018-03-06           796
1         2996       Centar    2022-09-24  2024-04-03           558
2         2996       Centar    2024-08-26  2025-09-18           389
3         2996       Centar    2019-07-01  2019-09-12            74
4         2996       Centar    2018-03-12  2018-04-18            38
5         2996       Centar    2021-04-01  2021-04-27            27
6         2996       Centar    2018-06-27  2018-07-11            15
7         2996       Centar    2018-12-02  2018-12-16            15
8         2996       Centar    2021-05-04  2021-05-16            13
9         2996       Centar    2020-07-05  2020-07-15            11
10        2996       Centar    2024-08-15  2024-08-24            10
11        2996       Centar    2021-06-03  2021-06-11             9
12        2996       Centar    2021-07-25  2021-08-02             9
13        2996       Centar    2022-02-22  2022-03-02             9
14        2996       Centar    2019-02-05  2019-02-12             8
15        2996       Centar    2020-07-29  2020-08-05             8
16        2996       Centar    2021-06-24  2021-07-01             8
17        2996       Centar    2019-05-03  2019-05-09             7
18        2996       Centar    2020-06-20  2020-06-26             7
19        2996       Centar    2021-05-21  2021-05-27             7
20        2996       Centar    2021-07-06  2021-07-12             7
21        2996       Centar    2021-08-07  2021-08-13             7
22        2996       Centar    2022-07-02  2022-07-08             7
23        2919    Gazi Baba    2016-01-01  2023-06-26          2734
24        2919    Gazi Baba    2024-08-26  2025-09-18           389
25        2919    Gazi Baba    2024-03-11  2024-03-26            16
26        2919    Gazi Baba    2023-09-14  2023-09-24            11
27        2919    Gazi Baba    2024-08-15  2024-08-24            10
28        2977       Karpos    2016-01-01  2018-03-06           796
29        2977       Karpos    2022-09-24  2024-04-01           556
30        2977       Karpos    2024-08-26  2025-09-18           389
31        2977       Karpos    2018-08-10  2018-10-30            82
32        2977       Karpos    2018-03-12  2018-04-18            38
33        2977       Karpos    2019-05-22  2019-06-13            23
34        2977       Karpos    2018-12-02  2018-12-16            15
35        2977       Karpos    2021-05-04  2021-05-16            13
36        2977       Karpos    2018-05-31  2018-06-11            12
37        2977       Karpos    2020-07-05  2020-07-15            11
38        2977       Karpos    2024-08-15  2024-08-24            10
39        2977       Karpos    2021-07-25  2021-08-02             9
40        2977       Karpos    2022-02-22  2022-03-02             9
41        2977       Karpos    2019-02-05  2019-02-12             8
42        2977       Karpos    2020-07-29  2020-08-05             8
43        2977       Karpos    2018-06-22  2018-06-28             7
44        2977       Karpos    2019-05-03  2019-05-09             7
45        2977       Karpos    2020-06-20  2020-06-26             7
46        2977       Karpos    2021-05-21  2021-05-27             7
47        2976       Lisice    2016-01-01  2023-06-26          2734
48        2976       Lisice    2024-08-26  2025-09-18           389
49        2976       Lisice    2024-03-11  2024-03-26            16
50        2976       Lisice    2023-09-14  2023-09-24            11
51        2976       Lisice    2024-08-15  2024-08-24            10
52        2978  Miladinovci    2016-01-01  2023-06-26          2734
53        2978  Miladinovci    2024-08-26  2025-09-18           389
54        2978  Miladinovci    2024-03-11  2024-03-26            16
55        2978  Miladinovci    2023-09-14  2023-09-24            11
56        2978  Miladinovci    2024-08-15  2024-08-24            10
57        2979     Rektorat    2016-01-01  2025-12-31          3653